name: Build Sidecar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish single server sidecar
        run: |
          dotnet publish ./src/server/server.csproj \
            -c Release \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o ./publish

      # Create or use release and upload asset
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0   # or dynamically from git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload sidecar to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/server*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
