name: Build Sidecar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish single server sidecar
        run: |
          dotnet publish ./src/server/server.csproj \
            -c Release \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o ./publish

      - name: Create or update release
        run: |
          gh release view latest || gh release create latest --title "Latest Sidecar Release" --notes "Automated build"
          gh release upload latest ./publish/server* --clobber
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
