name: Build Sidecar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish single server sidecar
        run: |
          dotnet publish ./src/server/server.csproj \
            -c Release \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o ./publish

      - name: Upload single sidecar artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: ./publish/server*
